development:
  adapter: async
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: CableChat_production

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV["redis://rediscloud:q0fxpHBYYwPaLSqOiJdbIiedeuY2fGgR@redis-15172.c62.us-east-1-4.ec2.cloud.redislabs.com:15172"] %>
